apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark.name" . }}-cm
data:
  # edit from spark-2.3.1-bin-hadoop2.6/conf/spark-env.sh.template
  spark-env.sh: |
    export HADOOP_CONF_DIR={{ .Values.const.HADOOP_CONF_DIR }}
    export YARN_CONF_DIR={{ .Values.const.YARN_CONF_DIR }}