apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.name" . }}-lb-svc
spec:
  selector:
    # select pod who has special label
    component: {{ include "spark.name" . }}-master
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      name: web-ui-port
    - port: 7077
      protocol: TCP
      name: inner-tcp-port
      
      